version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - apt-get update && apt-get install -y docker.io

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t react-app .
      - echo "Docker image built successfully"

  post_build:
    commands:
      - echo "Running Docker container"
      - docker run -d --name react-app -p 80:80 react-app
      - echo "Deployment complete, container running"
